name: joan-test-secret-workflow
on: push
      branches:
        -v1.9.0
jobs:
  simple:
    runs-on: ubuntu-latest
    environment: test_env_var
    steps:
      - name: test secrets
        with:
            env_secret: ${{ secrets.TEST_SECRET }}
        run: |
          echo "managed to grab secret"
