name: joan-test-secret-workflow
on: 
  push:
      branches:
        - v1.9.0
jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.JOANS_SECRET }}
            aws-secret-access-key: ${{ secrets.JOANS_SECRET }}
            aws-region: us-west-2
