name: joan-test-secret-workflow
on: 
  push:
      branches:
        - v1.9.0
      paths:
        - '**/joan_test_workflow.yml'
jobs:
  simple:
    runs-on: ubuntu-latest
    environment: test_env_var
    steps:
      - name: Check out test branch
        uses: actions/checkout@v2.3.4
        with:
          ref: v1.9.0
      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
            aws-region: us-west-2
      - name: Run build script
        run: |
          DIST_OUTPUT_BUCKET=msam-dev-us-west-2
          SOLUTION_NAME=aws-media-services-application-mapper
          VERSION=v1.9.0
          export PATH="$HOME/.local/bin:$PATH"
          env
          pip install testresources
          pip install --quiet --upgrade --force-reinstall -r source/msam/requirements.txt
          cd deployment
          ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
          ls -lah /home/runner/work/aws-media-services-application-mapper/aws-media-services-application-mapper/deployment/*
