name: joan-test-secret-workflow
# global environment variables to all jobs
env: 
  TEST_BRANCH: v1.9.0
  VERSION: v1.9.0
  REGION: us-west-2
  DIST_OUTPUT_BUCKET: msam-dev
  SOLUTION_NAME: aws-media-services-application-mapper
on: 
  push:
      branches:
        - $TEST_BRANCH
      paths:
        - '**/joan_test_workflow.yml'
jobs:
  simple:
    runs-on: ubuntu-latest
    environment: test_env_var
    steps:
      - name: Check out test branch
        uses: actions/checkout@v2.3.4
        with:
          ref: $TEST_BRANCH
      - name: Initialize AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
            aws-region: $REGION
      - name: Install required system packages
        run: |
          pip install testresources
          pip install --quiet --upgrade --force-reinstall -r source/msam/requirements.txt
          if [ $? -ne 0 ]; then
            echo "ERROR: Installing system packages."
            exit 1
          fi
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Run build script
        run: |
          cd deployment
          ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION
      - name: Deploy to S3
        run: |
          #ls -lah /home/runner/work/aws-media-services-application-mapper/aws-media-services-application-mapper/deployment/*
          cd $RUNNER_WORKSPACE/$SOLUTION_NAME/deployment
          ./deploy.sh -b $DIST_OUTPUT_BUCKET -s $SOLUTION_NAME -v $VERSION -r us-west-2 -a none -t dev
