on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pull-request-workflow:
    runs-on: ubuntu-latest
    name: Scan pull request content for security issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: ClamAV Scan
        uses: djdefi/gitavscan@main
        with:
          full: '--full'
      - name: Trufflehog Scan
        uses: edplato/trufflehog-actions-scan@master
        with:
          scanArguments: "--regex --entropy=False"

      # - name: Security scan step
      #   uses: ./.github/actions/security-scan
      #   id: security-scan-test
      #   with:
      #     who-to-greet: 'MSAM Contributor'
      # Use the output from the `hello` step
      # - name: Get the output time
      #   run: echo "The time was ${{ steps.hello.outputs.time }}"
